package br.com.correntista.entidade;

public enum TipoInatividade {

	FINALIZACAO_AUTOMATICA,
	ESTAGIARIO_EFETIVADO,
	DESENTENDIMENTO_EMPRESA,
	DESENTENDIMENTO_ESTAGIARIO,
	DESENTENDIMENTO_AMBOS,
	TRANCAMENTO_MATRICULA
	
}
