package br.com.correntista.entidade;

public enum TipoInatividade {

	ESTAGIARIO_NAO_EFETIVADO,
	ESTAGIARIO_EFETIVADO,
	DESAPROVACAO_EMPRESA,
	DESAPROVACAO_ESTAGIARIO,
	DESAPROVACAO_AMBOS,
	TRANCAMENTO_MATRICULA
	
}
