-- drop database petshop;
-- create database petshop;

USE PETSHOP;

# DML PARA TESTES
INSERT INTO COMPORTAMENTO (ID, TIPO, DESCRICAO)
	VALUES (1, 'AGRESSIVO', 'Animal agitado e sem controle');
INSERT INTO COMPORTAMENTO (ID, TIPO, DESCRICAO)
	VALUES (2, 'NORMAL', 'Comportamendo dentro do padrão');
INSERT INTO COMPORTAMENTO (ID, TIPO, DESCRICAO)
	VALUES (3, 'MEDROSO', 'Animal amedrontado');

INSERT INTO DONO (ID, CPF, EMAIL, NOME, TELEFONE)
	VALUES (1, '123.456.789-98', 'fulano@email.com', 'Fulano de Tal', '(48)3244-6899');

INSERT INTO ENDERECO (ID, BAIRRO, CEP, COMPLEMENTO, LOCALIDADE, LOGRADOURO, NUMERO, UF, ID_DONO)
	VALUES (1, 'Centro', '88020-210', 'Casa', 'Florianópolis', 'Rua Menino Deus', '32', 'SC', 1);


/* testes no banco */
/*SELECT * FROM COMPORTAMENTO;

SELECT * FROM DONO D INNER JOIN ENDERECO E ON D.ID = E.ID_DONO;
SELECT * FROM DONO;
SELECT * FROM ENDERECO;

SELECT * FROM ANIMAL;
SELECT * FROM GATO;
SELECT * FROM ANIMAL A INNER JOIN GATO G ON A.ID = G.ID_ANIMAL;

SELECT * FROM CACHORRO;
SELECT * FROM ANIMAL A INNER JOIN CACHORRO C ON A.ID = C.ID_ANIMAL;

SELECT * FROM CONSULTA;*/
